schema_version = "1.3.0"
id = "scene_staticmesh_ue5_toolkit"
version = "1.3.0"
name = "Scene StaticMesh - UE5 Workflow Toolkit"
tagline = "Smart collisions, naming, and batch export for Unreal Engine 5"
maintainer = "Lp Moonkey Dev <lpmoonkeydev@gmail.com>"
type = "add-on"
license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.2.0"
tags = ["Import-Export", "Mesh"]

website = "https://github.com/LPesposito/SSM_UE5_Blender_Toolkit"

[permissions]
files = "Required for exporting FBX files and saving textures to disk"